service: trustee-transactions
frameworkVersion: '3'

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: ../../webpack.config.js
    packager: 'npm'

provider:
    name: aws
    runtime: nodejs16.x
    region: eu-central-1
    versionFunctions: false
    stage: ${opt:stage, 'dev'}
    apiGateway:
        restApiId: !ImportValue TrusteeRestApiGatewayId-${self:provider.stage}
        restApiRootResourceId: !ImportValue TrusteeRestApiGatewayRootResourceId-${self:provider.stage}
    environment:
        USER_POOL_ID: !ImportValue TrusteeUserPool
        USER_POOL_CLIENT_ID: !ImportValue TrusteeUserPoolClient
        REGION: !Ref AWS::Region
        STAGE: ${self:provider.stage}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:Query
          Resource: !ImportValue TrusteeMainTableArn-${self:provider.stage}
        - Effect: Allow
          Action:
              - dynamodb:Query
          Resource:
            Fn::Join:
              - ""
              - - !ImportValue TrusteeMainTableArn-${self:provider.stage}
                - /index/GSI1

functions:
    GetTransactions:
        handler: functions/getTransactions.handler
        events:
            - http:
                  method: GET
                  path: /transactions
                  cors: true
                  authorizer:
                      name: AuthAuthorizer
                      type: COGNITO_USER_POOLS
                      arn: !ImportValue TrusteeUserPoolArn-${self:provider.stage}
                      claims:
                          - email
    GetWallets:
        handler: functions/getWallets.handler
        events:
            - http:
                  method: GET
                  path: /wallets
                  cors: true
                  authorizer:
                      name: AuthAuthorizer
                      type: COGNITO_USER_POOLS
                      arn: !ImportValue TrusteeUserPoolArn-${self:provider.stage}
                      claims:
                          - email
