version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trustee-storage"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tx0gyqj9k8y3"
s3_prefix = "trustee-storage"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
