version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "trustee"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tx0gyqj9k8y3"
s3_prefix = "trustee"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
