AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud infrastructure for the back-end of the Trustee platform

Globals:
  Function:
    Timeout: 2
    Runtime: nodejs14.x
    Architectures:
      - x86_64

Parameters:
  Stage:
    Type: String
    Default: dev
