AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud infrastructure for the back-end of the Trustee platform

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs16.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        USER_POOL_ID: !ImportValue TrusteeUserPool
        USER_POOL_CLIENT: !ImportValue TrusteeUserPoolClient
        REGION: !Ref AWS::Region

Parameters:
  Stage:
    Type: String
    Default: dev

Resources:
  RestApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: trustee
      StageName: !Ref Stage
      Cors:
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowOrigin: "'*'"
  # Functions
  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: signUp.handler
      Events:
        SignUp:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiGateway
            Path: /users
            Method: POST
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminSetUserPassword
              Resource: !ImportValue TrusteeUserPoolArn
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: arn:aws:dynamodb:eu-central-1:471417226823:table/trustee
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - signUp.ts

Outputs:
  RestApiGatewayURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
