AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM CLI Nested Stack for Auto Dependency Layer Creation
Metadata:
  SamCliInfo: 1.49.0
  key: AWS SAM CLI sync command
Outputs:
  SignUpFunctionbbef62ecDepLayer:
    Value:
      Ref: SignUpFunctionbbef62ecDepLayer
Resources:
  SignUpFunctionbbef62ecDepLayer:
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      CompatibleRuntimes:
      - nodejs14.x
      ContentUri: D:\General\Personal\GithubWorks\trustee-backend\.aws-sam\auto-dependency-layer\SignUpFunctionbbef62ecDepLayer
      Description: Auto created layer for dependencies of function SignUpFunction
      LayerName: trustee67dfdf5e-SignUpFunctionbbef62ec-DepLayer
      RetentionPolicy: Delete
    Type: AWS::Serverless::LayerVersion
Transform: AWS::Serverless-2016-10-31
