service: trustee-transactions
frameworkVersion: "3"

plugins:
    - serverless-webpack

package:
    individually: true

custom:
    webpack:
        webpackConfig: ../../../webpack.config.js
        packager: "npm"

provider:
    name: aws
    runtime: nodejs18.x
    region: eu-central-1
    versionFunctions: false
    stage: ${opt:stage, 'dev'}
    apiGateway:
        restApiId: !ImportValue TrusteeRestApiGatewayId-${self:provider.stage}
        restApiRootResourceId: !ImportValue TrusteeRestApiGatewayRootResourceId-${self:provider.stage}
    environment:
        DB_HOST: ${file(../../../env/env.${self:provider.stage}.json):DB_HOST}
        DB_USERNAME: ${file(../../../env/env.${self:provider.stage}.json):DB_USERNAME}
        DB_PASSWORD: ${file(../../../env/env.${self:provider.stage}.json):DB_PASSWORD}
        DB_NAME: ${file(../../../env/env.${self:provider.stage}.json):DB_NAME}
        DB_PORT: ${file(../../../env/env.${self:provider.stage}.json):DB_PORT}
        USER_POOL_ID: !ImportValue TrusteeUserPool
        USER_POOL_CLIENT_ID: !ImportValue TrusteeUserPoolClient
        REGION: !Ref AWS::Region
        STAGE: ${self:provider.stage}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
          Resource: !ImportValue TrusteeMainTableArn-${self:provider.stage}
        - Effect: Allow
          Action:
              - dynamodb:Query
          Resource:
              Fn::Join:
                  - ""
                  - - !ImportValue TrusteeMainTableArn-${self:provider.stage}
                    - /index/GSI1
        - Effect: Allow
          Action:
              - dynamodb:Query
          Resource:
              Fn::Join:
                  - ""
                  - - !ImportValue TrusteeMainTableArn-${self:provider.stage}
                    - /index/GSI2

functions:
    GetTransactions:
        handler: functions/getTransactions.handler
        events:
            - http:
                  method: GET
                  path: /transactions
                  cors: true
                  authorizer:
                      type: COGNITO_USER_POOLS
                      authorizerId: !ImportValue TrusteeAuthorizerId-${self:provider.stage}
                      claims:
                          - email
    GetBalance:
        handler: functions/getBalance.handler
        events:
            - http:
                  method: GET
                  path: /transactions/balance
                  cors: true
                  authorizer:
                      type: COGNITO_USER_POOLS
                      authorizerId: !ImportValue TrusteeAuthorizerId-${self:provider.stage}
                      claims:
                          - email
    GetTransactionCategories:
        handler: functions/getTransactionCategories.handler
        events:
            - http:
                  method: GET
                  path: /transaction-categories
                  cors: true
                  authorizer:
                      type: COGNITO_USER_POOLS
                      authorizerId: !ImportValue TrusteeAuthorizerId-${self:provider.stage}
                      claims:
                          - email
    CreateTransactionCategory:
        handler: functions/createTransactionCategory.handler
        events:
            - http:
                  method: POST
                  path: /transaction-categories
                  cors: true
                  authorizer:
                      type: COGNITO_USER_POOLS
                      authorizerId: !ImportValue TrusteeAuthorizerId-${self:provider.stage}
                      claims:
                          - email
    CreateTransaction:
        handler: functions/createTransaction.handler
        events:
            - http:
                  method: POST
                  path: /transactions
                  cors: true
                  authorizer:
                      type: COGNITO_USER_POOLS
                      authorizerId: !ImportValue TrusteeAuthorizerId-${self:provider.stage}
                      claims:
                          - email
    UpdateTransaction:
        handler: functions/updateTransaction.handler
        events:
            - http:
                  method: PUT
                  path: /transactions/{id}
                  cors: true
                  authorizer:
                      type: COGNITO_USER_POOLS
                      authorizerId: !ImportValue TrusteeAuthorizerId-${self:provider.stage}
                      claims:
                          - email
    DeleteTransaction:
        handler: functions/deleteTransaction.handler
        events:
            - http:
                  method: DELETE
                  path: /transactions
                  cors: true
                  authorizer:
                      type: COGNITO_USER_POOLS
                      authorizerId: !ImportValue TrusteeAuthorizerId-${self:provider.stage}
                      claims:
                          - email
